import { VoxelModelData } from "../VoxelModel.types";
import { VoxelGeometryData } from "../../Geometry/VoxelGeometry.types";
export declare const chainGeometry: VoxelGeometryData;
export declare const chainModel: VoxelModelData;
export declare const carpetGeometry: VoxelGeometryData;
export declare const carpetModel: VoxelModelData;
export declare const fencePost: VoxelGeometryData;
export declare const fenceEastWest: VoxelGeometryData;
export declare const fenceNorthsouth: VoxelGeometryData;
export declare const fence: VoxelModelData;
export declare const candlesGeometry1: VoxelGeometryData;
export declare const candlesGeometry2: VoxelGeometryData;
export declare const candlesGeometry3: VoxelGeometryData;
export declare const candlesGeometry4: VoxelGeometryData;
export declare const candlesModel: VoxelModelData;
export declare const leverGeometryBase: VoxelGeometryData;
export declare const leverGeometryDown: VoxelGeometryData;
export declare const leverGeometry: VoxelGeometryData[];
export declare const leverModel: VoxelModelData;
export declare const diamondGeometry: VoxelGeometryData;
export declare const diamondModel: VoxelModelData;
export type BeachShadeVoxelModelArgs = {
    poleTexture: number;
    canopyTexture: number;
};
export declare const beachShadeGeometry: VoxelGeometryData;
export declare const beachShadeModel: VoxelModelData;
